### ISSUE TITLE
error on patching

### ISSUE THREAD

**Issue by mcleod777** [tr4wzified/KnowYourArmorPatcher#18]
System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JArray'.
   at KnowYourArmorPatcher.Program.RunPatch(IPatcherState`2 state) in C:\Users\Bob\AppData\Local\Temp\Synthesis\czbbgtdi.hm0\Git\cab4xis5.v5m\Runner\KnowYourArmorPatcher\Program.cs:line 287
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 94
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 456
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 404
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 378
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)

**Comment by tr4wzified** [comment]
Try deleting `C:\Users\Bob\AppData\Local\Temp\Synthesis\` and redownload the patcher.

**Comment by mcleod777** [comment]
Thank you.  I’m running to zedit version of know your Amor now.  Is the
synthesis patch version needed to work along side of the original zedit
version?
Caleb

**Comment by tr4wzified** [comment]
No, the Synthesis patcher is standalone and replaces the zEdit patcher.

**Comment by mcleod777** [comment]
thanks again............  sounds like I need the .esp from know your armor mod.  But I don't need to run the zedit patcher?  Is that correct?

**Comment by mcleod777** [comment]
https://puu.sh/Ie7je/f902cf41f3.jpg

I just tried to run the patcher again and failed.  Can you see the snapshot in the link above and tell me If you see something i did wrong?  Thanks
caleb

**Comment by tr4wzified** [comment]
Is Living Skyrim using Know Your Enemy 8 or 9? If you're using 8 you might want to switch to the 'kye8' branch (you can manually type it in Synthesis).

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcleod777** [comment]
https://puu.sh/Ie7qn/22f6a6d9c0.jpg

version 9.0.1   latest

**Comment by tr4wzified** [comment]
And removing the temporary folder didn´t work right? I'll have a look when I have some time then.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcleod777** [comment]
right.............  thank you

**Comment by Deapper** [comment]
same error

**Comment by tr4wzified** [comment]
See https://github.com/tr4wzified/KnowYourArmorPatcher/issues/21 for a fix
