### ISSUE TITLE
Error when Patching

### ISSUE THREAD

**Issue by yiztj1259** [tr4wzified/KnowYourArmorPatcher#19]
Compiling
(C:\Users\YizTJ\AppData\Local\Temp\Synthesis\uriwlp5d.0ly\Git\nsabojpu.gfz\Runner\KnowYourArmorPatcher): dotnet build --runtime win-x64 "KnowYourArmorPatcher.csproj" -c Release
Extra data folder already exists. Leaving as is: D:\Games\Tools\Synthesis\Data\KnowYourArmorPatcher
Compiled
Sha 0fdf3c61c4f8034ddabbb7147aa09381dfeac77a
(): dotnet run --project "C:\Users\YizTJ\AppData\Local\Temp\Synthesis\uriwlp5d.0ly\Git\nsabojpu.gfz\Runner\KnowYourArmorPatcher\KnowYourArmorPatcher.csproj" -c Release --runtime win-x64 --no-build check-runnability --DataFolderPath D:\Games\Offline\Skyrim\Data --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\YizTJ\AppData\Local\Temp\Synthesis\uriwlp5d.0ly\Workspace\Plugins.txt
Running
(): dotnet run --project "C:\Users\YizTJ\AppData\Local\Temp\Synthesis\uriwlp5d.0ly\Git\nsabojpu.gfz\Runner\KnowYourArmorPatcher\KnowYourArmorPatcher.csproj" --runtime win-x64 --no-build -c Release run-patcher --DataFolderPath D:\Games\Offline\Skyrim\Data --ExtraDataFolder D:\Games\Tools\Synthesis\Data\KnowYourArmorPatcher --DefaultDataFolderPath C:\Users\YizTJ\AppData\Local\Temp\Synthesis\uriwlp5d.0ly\Git\nsabojpu.gfz\Runner\KnowYourArmorPatcher\Data --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\YizTJ\AppData\Local\Temp\Synthesis\uriwlp5d.0ly\Workspace\Plugins.txt --OutputPath "C:\Users\YizTJ\AppData\Local\Temp\Synthesis\uriwlp5d.0ly\Workspace\0 - KnowYourArmorPatcher" --PatcherName KnowYourArmorPatcher --PersistencePath C:\Users\YizTJ\AppData\Local\Temp\Synthesis\uriwlp5d.0ly\Persistence
Mutagen version: 0.32
Mutagen sha: b9ecd83527de2313df5b1e1b33fab451c4df28b3
Synthesis version: 0.19.4
Synthesis sha: 35e30ef2f0373de308999718f7d55ca10ad8a859
run-patcher --DataFolderPath D:\Games\Offline\Skyrim\Data --ExtraDataFolder D:\Games\Tools\Synthesis\Data\KnowYourArmorPatcher --DefaultDataFolderPath C:\Users\YizTJ\AppData\Local\Temp\Synthesis\uriwlp5d.0ly\Git\nsabojpu.gfz\Runner\KnowYourArmorPatcher\Data --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\YizTJ\AppData\Local\Temp\Synthesis\uriwlp5d.0ly\Workspace\Plugins.txt --OutputPath "C:\Users\YizTJ\AppData\Local\Temp\Synthesis\uriwlp5d.0ly\Workspace\0 - KnowYourArmorPatcher" --PatcherName KnowYourArmorPatcher --PersistencePath C:\Users\YizTJ\AppData\Local\Temp\Synthesis\uriwlp5d.0ly\Persistence
Prepping state.
Using TextFileSharedFormKeyAllocator allocator
Reading settings: D:\Games\Tools\Synthesis\Data\KnowYourArmorPatcher\settings.json
*** DETECTED SETTINGS ***
effect_intensity: 1
*************************
System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JArray'.
   at KnowYourArmorPatcher.Program.RunPatch(IPatcherState`2 state) in C:\Users\YizTJ\AppData\Local\Temp\Synthesis\uriwlp5d.0ly\Git\nsabojpu.gfz\Runner\KnowYourArmorPatcher\Program.cs:line 287
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 94
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 456
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 404
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 378
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)

**Comment by yiztj1259** [comment]
Look like it's the same issue as this one
https://github.com/tr4wzified/KnowYourArmorPatcher/issues/18

I did try to delete the Synthesis temp folder but it's still not working.
