### ISSUE TITLE
Incompatibility With Creation Club Mods

### ISSUE THREAD

**Issue by Smellsin** [tr4wzified/KnowYourArmorPatcher#5]
I had gotten a error message when running both of the patchers Know Your Armor and Know You Enemy, in which the error looks like it said that the master for the file was missing, but the master was itself:
<details> 
  <summary>Error Information </summary>
   Mutagen.Bethesda.MissingModException: A referenced mod was not present on the load order being sorted against: ccTWBSSE001-PuzzleDungeon.esm.  This mod was referenced by MajorRecord: 000893:ccTWBSSE001-PuzzleDungeon.esm
   at Mutagen.Bethesda.Internals.ModHeaderWriteLogic.SortMasters(List`1 modKeys)
   at Mutagen.Bethesda.Internals.ModHeaderWriteLogic.ConstructWriteMasters(IModGetter mod)
   at Mutagen.Bethesda.Internals.ModHeaderWriteLogic.PostProcessAdjustments(MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader)
   at Mutagen.Bethesda.Internals.ModHeaderWriteLogic.WriteHeader(BinaryWriteParameters param, MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimModCommon.WriteParallel(ISkyrimModGetter item, Stream stream, BinaryWriteParameters param, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.SkyrimModMixIn.WriteToBinaryParallel(ISkyrimModGetter item, String path, BinaryWriteParameters param)
   at Mutagen.Bethesda.Skyrim.SkyrimMod.Mutagen.Bethesda.IModGetter.WriteToBinaryParallel(String path, BinaryWriteParameters param)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Patch[TMod,TModGetter](RunSynthesisMutagenPatcher settings, PatcherFunction`2 patcher, UserPreferences userPreferences)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass4_0`2.<Patch>b__1(RunSynthesisMutagenPatcher settings)
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher 
</details>

Yeah, really weird, but issues with Creation Club mods have always affected anything for Skyrim SE lol. Thank you for the great patcher too, never suspected to get something this good so soon.

**Comment by tr4wzified** [comment]
Should be fixed if using the latest Synthesis version
